### ISSUE TITLE
Same card details accepted more than once for same wallet.

### ISSUE THREAD

**Issue by imbudhiraja** [lemonwaysas/node-js-client-directkit-json#1]
I'm using the sandbox version of the lemon way api and i'm able to add one card (Test Card - 5017670000006700, 5017670000001800) more than one time with same wallet id.  Please let me know what's wrong with api.

**Comment by imbudhiraja** [comment]
@duongphuhiep any update on this?

**Comment by duongphuhiep** [comment]
I appologize for the delay,

it is normal, we don't store the card number on our side.

For each register card, a "fake" debit transaction (amount 1 euro) will be created (on bank side), the card information is tokenized along with this transaction. We all use this token to identify the card on bank side in the future. 

It is normal that the same card might be registered multiple time, each time with a different token.

regards
